### ISSUE TITLE
Мокап для игрового процесса

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/2019-ux-sea-battle#45]
Продумать, как будет выглядеть экран битвы и как игрок будет взаимодействовать с ним.

**Comment by logolent** [comment]
https://www.figma.com/file/7qTWFf2neStE010L9bfoU7/UI-%D0%9C%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%B9-%D0%B1%D0%BE%D0%B9-draft-Copy?node-id=709%3A70
